require:
 - rubocop-rails
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'build/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'hyrax-migrator.gemspec'
    - 'spec/**/*'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'

RSpec/LetSetup:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/Present:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

Layout/LineLength:
  Enabled: false
