version: '3'

networks:
  ? external
  ? internal

services:
  ##
  # Basic Rails application build image
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/data # mount current directory into the image
    # use tmpfs for tmp and log for performance and to allow
    # multiple builds in parallel. Both directories are mounted
    # into the image AFTER the working directory is mounted.
    tmpfs:
      - /data/log
    networks:
      ? external
      ? internal
    expose:
      - 3000
  server:
    <<: *app
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
    command: >
      bash -c "rm -f spec/dummy/tmp/pids/server.pid && bundle exec rails s"
  test:
    <<: *app
    environment:
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=1
    command: >
      bash -c "rm -f spec/dummy/tmp/pids/server.pid && bundle exec rails s -e test -p 3001"
    expose:
      - 3001
